---
title: "SSTI 090 Report - Results"
author: "Ryan Johnson"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(drake)
library(tidyverse)
library(RColorBrewer)
library(phyloseq)

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
theme_set(theme_minimal())
plot_color <- colorRampPalette(brewer.pal(8, "Set1"))(12)
```

# Relative Abundance

```{r}
# Calculate Phylum Relative Abundance
phylum_relabundance <- psmelt(readd(ps_phylum_relabun))

# Functions ----------------------------------------------------
# Stacked Bar plot
stacked_bar_plot_phylum <- function(body_site){
  phylum_relabundance %>% 
    filter(Body_Site == body_site) %>% 
    ggplot(aes(x = Sample, y = Abundance, fill = phylum)) +
    geom_bar(stat = "identity") +
    labs(x = "",
         y = "Relative Abundance") +
    facet_wrap(~ Day, scales = "free") +
    scale_fill_manual(values = plot_color, na.value = "black") +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_text(size = 12),
      legend.text = element_text(size = 10),
      strip.text = element_text(size = 12)
  )
}

boxplot_phylum <- function(body_site){
  phylum_relabundance %>% 
    filter(Sample_Group %in% c("Control", "SSTI")) %>% 
    filter(Body_Site == body_site) %>% 
    ggplot(aes(x = phylum, y = Abundance, fill = Sample_Group)) +
    geom_boxplot() +
    ylim(0, 100) +
    labs(x = "",
         y = "Relative Abundance") +
    facet_wrap(~ Day, scales = "free") +
    theme(
      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
      axis.text.y = element_text(size = 12),
      legend.text = element_text(size = 10),
      strip.text = element_text(size = 12)
  )
}
```


## Phylum Relative Abundance by Day {.tabset}

### Nares

```{r fig.height=5, fig.width=9}
stacked_bar_plot_phylum("Nares")
```

### Oropharynx

```{r fig.height=5, fig.width=9}
stacked_bar_plot_phylum("Oropharynx")
```

### Inguinal

```{r fig.height=5, fig.width=9}
stacked_bar_plot_phylum("Inguinal")
```

### Perianal

```{r fig.height=5, fig.width=9}
stacked_bar_plot_phylum("Perianal")
```

### Abscess

```{r fig.height=5, fig.width=9}
stacked_bar_plot_phylum("Abscess")
```


## Phylum Relative Abundance by Day: SSTI vs Controls {.tabset}

### Nares

```{r fig.height=5, fig.width=9}
boxplot_phylum("Nares")
```

### Oropharynx

```{r fig.height=5, fig.width=9}
boxplot_phylum("Oropharynx")
```

### Inguinal

```{r fig.height=5, fig.width=9}
boxplot_phylum("Inguinal")
```

### Perianal

```{r fig.height=5, fig.width=9}
boxplot_phylum("Perianal")
```




## Genus Relative Abundance by Day

```{r}

```

